# Poziom 1 - Czyszczenie i integracja danych

In [1]:
import pandas as pd
from google.cloud import bigquery

## Część 2

Uzyskaj dostęp do danych nt. COVID-19 z poziomu Pythona.

#### **2.5.** Uruchom klienta BigQuery z poziomu Pythona.

In [2]:
from dotenv import load_dotenv

load_dotenv()

client = bigquery.Client()

#### **2.6.** Pobierz dane do obiektu DataFrame.

In [3]:
query = """
    SELECT *
    FROM bigquery-public-data.covid19_open_data.covid19_open_data LIMIT 10
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

,location_key,date,place_id,wikidata_id,datacommons_id,country_code,country_name,iso_3166_1_alpha_2,iso_3166_1_alpha_3,aggregation_level,...,cumulative_vaccine_doses_administered_pfizer,new_persons_fully_vaccinated_moderna,cumulative_persons_fully_vaccinated_moderna,new_vaccine_doses_administered_moderna,cumulative_vaccine_doses_administered_moderna,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,location_geometry
0,AR,2020-08-26,ChIJZ8b99fXKvJURqA_wKpl3Lz0,Q414,country/ARG,AR,Argentina,AR,ARG,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-64 -34)
1,AR,2021-07-22,ChIJZ8b99fXKvJURqA_wKpl3Lz0,Q414,country/ARG,AR,Argentina,AR,ARG,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-64 -34)
2,AR,2021-04-18,ChIJZ8b99fXKvJURqA_wKpl3Lz0,Q414,country/ARG,AR,Argentina,AR,ARG,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-64 -34)
3,AR,2022-01-30,ChIJZ8b99fXKvJURqA_wKpl3Lz0,Q414,country/ARG,AR,Argentina,AR,ARG,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-64 -34)
4,AR,2020-07-02,ChIJZ8b99fXKvJURqA_wKpl3Lz0,Q414,country/ARG,AR,Argentina,AR,ARG,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-64 -34)
5,BR,2020-11-14,ChIJzyjM68dZnAARYz4p8gYVWik,Q155,country/BRA,BR,Brazil,BR,BRA,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-53 -14)
6,BR,2021-03-07,ChIJzyjM68dZnAARYz4p8gYVWik,Q155,country/BRA,BR,Brazil,BR,BRA,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-53 -14)
7,BR,2020-01-18,ChIJzyjM68dZnAARYz4p8gYVWik,Q155,country/BRA,BR,Brazil,BR,BRA,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-53 -14)
8,BR,2020-07-05,ChIJzyjM68dZnAARYz4p8gYVWik,Q155,country/BRA,BR,Brazil,BR,BRA,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-53 -14)
9,BR,2020-01-09,ChIJzyjM68dZnAARYz4p8gYVWik,Q155,country/BRA,BR,Brazil,BR,BRA,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POINT(-53 -14)

## Część 3
**Misja dodatkowa – Poznanie danych**

Zapoznaj się z informacjami o danych na temat COVID-19.

#### 3.1. Sprawdź, ile jest zapisanych wierszy z danymi.

In [4]:
query = """
    SELECT COUNT(*) AS rows_count
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

   rows_count
0    22756333

#### 3.2. Sprawdź, ile krajów jest uwzględnionych w danych.

In [5]:
query = """
    SELECT COUNT(DISTINCT country_code) AS countries_count
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

   countries_count
0              246

#### 3.3. Sprawdź, w jaki sposób zapisywane są dzienne informacje dla krajów.

Dzienne informacje (np. nowe przypadki, nowe zgony, nowe szczepienia) są zapisywane w postaci 2 wartości:
- liczba nowych przypadków danego dnia
- całkowita liczba przypadków w danym dniu

Dane są zapisywane dla różnych stopni agregacji względem lokalizacji (np. kraj, stan, hrabstwo, miasto). Dane są zapisywane z częstotliwością dzienną.

Przykładowe kolumny (dla nowych przypadków):

In [6]:
query = """
    SELECT location_key, date, aggregation_level
        new_confirmed, cumulative_confirmed
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
    LIMIT 10
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

  location_key        date  new_confirmed  cumulative_confirmed
0        ES_CT  2020-05-29              1                 73995
1        ES_CT  2021-05-25              1                723743
2        ES_CT  2021-12-03              1               1069463
3        US_AL  2020-09-05              1                131803
4        US_AL  2020-09-20              1                144962
5        US_AL  2020-08-04              1                 93702
6        US_AR  2021-02-19              1                314713
7        US_AZ  2020-11-01              1                247473
8        US_AZ  2020-06-28              1                 73908
9        US_CA  2021-04-20              1               3723405

#### 3.4. Sprawdź, w jaki sposób zapisywane są wartości liczbowe.

Wartości liczbowe zapisywane są w postaci liczb całkowitych lub zmiennoprzecinkowych. Wartości są zapisywane w kolumnach o typach danych INTEGER, FLOAT lub STRING.

Zawierające wartości liczbowe kolumny o typie danych STRING bezproblemowo przechodzą konwersję na typ zmiennoprzecinkowy, co może sugerować, że typ danych kolumny został źle określony:

In [7]:
query = """
    SELECT new_tested, population_largest_city, population_clustered,
    human_capital_index, area_rural_sq_km, area_urban_sq_km,
    life_expectancy, adult_male_mortality_rate, adult_female_mortality_rate,
    pollution_mortality_rate, comorbidity_mortality_rate, mobility_retail_and_recreation,
    mobility_grocery_and_pharmacy, mobility_parks, mobility_transit_stations,
    mobility_workplaces, mobility_residential
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

_ = query_result.to_dataframe().astype(float)

#### 3.5. Sprawdź, jaki przedział czasowy jest uwzględniony w danych. Dodatkowo porównaj przedziały czasowe dla przypadków nowych zachorowań, nowych śmierci oraz nowych zaszczepionych osób w danych.

In [8]:
query = """
    SELECT RANGE(MIN(date), MAX(DATE)) AS total_date_range,
        RANGE(
            MIN(CASE WHEN new_confirmed > 0 THEN date END),
            MAX(CASE WHEN new_confirmed > 0 THEN date END)
        ) AS new_confirmed_date_range,
        RANGE(
            MIN(CASE WHEN new_deceased > 0 THEN date END),
            MAX(CASE WHEN new_deceased > 0 THEN date END)
        ) AS new_deceased_date_range,
        RANGE(
            MIN(CASE WHEN new_persons_vaccinated > 0 THEN date END),
            MAX(CASE WHEN new_persons_vaccinated > 0 THEN date END)
        ) AS new_persons_vaccinated_date_range
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

date_ranges = query_result.to_dataframe()

In [9]:
date_ranges = date_ranges.T
date_ranges.columns = ['date_range']

date_ranges = date_ranges.assign(
    start=date_ranges['date_range'].apply(lambda x: x['start']),
    end=date_ranges['date_range'].apply(lambda x: x['end'])
)

date_ranges.drop(columns='date_range', inplace=True)

In [10]:
date_ranges

                                        start         end
total_date_range                   2020-01-01  2022-09-17
new_confirmed_date_range           2020-01-01  2022-09-15
new_deceased_date_range            2020-01-02  2022-09-15
new_persons_vaccinated_date_range  2020-12-07  2022-09-14

#### 3.6. Sprawdź więcej informacji (co najmniej 5 różnych) o danych dotyczących COVID-19. W tym celu nie wykonuj żadnych dodatkowych obliczeń.

##### 1. Czy w identyfikatorze lokalizacji (*location_key*) oraz dacie (*date*) są brakujące wartości?

In [11]:
query = """
    SELECT COUNTIF(location_key IS NULL) AS location_key_missing_values,
        COUNTIF(date IS NULL) AS date_missing_values
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

   location_key_missing_values  date_missing_values
0                            0                    0

##### 2. Czy każda para wartości identyfikatora lokalizacji (*location_key*) oraz daty (*date*) jest unikalna?

In [12]:
query = """
    SELECT location_key, date, COUNT(*) AS count
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
    GROUP BY location_key, date
    HAVING COUNT(*) > 1
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

Empty DataFrame
Columns: [location_key, date, count]
Index: []

##### 3. Ile jest poziomów agregacji danych względem lokalizacji oraz ile jest zapisanych wierszy z danymi dla poszczególnych poziomów?

In [13]:
query = """
    SELECT aggregation_level, COUNT(*) AS rows_count
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
    GROUP BY aggregation_level
    ORDER BY rows_count DESC
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe()

   aggregation_level  rows_count
0                  2    21061723
1                  1     1419112
2                  0      243786
3                  3       31712

##### 4. Jakie są przedziały wiekowe w przypadku podziału zapisanych danych w zależności od wieku?

In [14]:
query = """
    SELECT DISTINCT age_bin_0, age_bin_1, age_bin_2, age_bin_3, age_bin_4,
        age_bin_5, age_bin_6, age_bin_7, age_bin_8, age_bin_9
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

age_bins = query_result.to_dataframe()

In [15]:
age_bins.shape

(41, 10)

In [16]:
age_bins.head()

,age_bin_0,age_bin_1,age_bin_2,age_bin_3,age_bin_4,age_bin_5,age_bin_6,age_bin_7,age_bin_8,age_bin_9
0,00-09,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80-,None
1,00-10,11-20,21-30,31-40,41-50,51-60,61-70,71-80,81-,None
2,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-,None,None
3,00-17,18-24,25-49,50-64,65-74,75-,None,None,None,None
4,00-09,10-19,20-29,30-39,40-49,50-59,60-69,70-,None,None

##### 5. W jaki sposób zapisywane są dane dotyczące restrykcji spowodowanych pandemią COVID-19?

In [17]:
query = """
    SELECT school_closing, workplace_closing, cancel_public_events, restrictions_on_gatherings, public_transport_closing, stay_at_home_requirements, restrictions_on_internal_movement, international_travel_controls
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

query_result.to_dataframe().describe()

,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls
count,302415.0,302243.0,302068.0,301981.0,301845.0,302074.0,302034.0,300241.0
mean,1.471319,1.304182,1.245832,2.210308,0.500678,0.839917,0.899213,2.497783
std,1.075089,0.944901,0.788635,1.634293,0.660792,0.871215,0.83452,1.256683
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
50%,1.0,1.0,1.0,3.0,0.0,1.0,1.0,3.0
75%,2.0,2.0,2.0,4.0,1.0,2.0,2.0,3.0
max,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0

Kolumny zawierające informacje dotyczące restrykcji spowodowanych pandemią COVID-19 zawierają wartości liczbowe całkowite z zakresu 0-4, oznaczające wzrastający stopień restrykcji.

## Część 4

Przeanalizuj poniższe przypadki. Zastanów się, jakie dane potrzebujesz do każdego z nich, a następnie zapisz je w osobnych, jak najprostszych obiektach DataFrame. Na tym etapie nie przetwarzaj ich. Zadbaj o czystość danych, m.in. usuń niepotrzebne puste wartości i duplikaty, zunifikuj sposób podawania informacji, zaproponuj sposób naprawy błędnych danych. Gotowe dane z obiektów DataFrame zapisz w osobnych plikach CSV.

#### **4.1.** Chcemy posiadać podstawowe dane o wszystkich krajach świata, które będą zrozumiałe dla człowieka oraz uniwersalne i potencjalnie przyszłościowe do dalszego przetwarzania.

In [18]:
query = """
    SELECT location_key, date,
        country_name, aggregation_level,
        iso_3166_1_alpha_2, iso_3166_1_alpha_3,
        subregion1_code, subregion1_name,
        subregion2_code, subregion2_name,
        population, gdp_usd,
        nurses_per_1000, physicians_per_1000,
        hospital_beds_per_1000, health_expenditure_usd
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

df_countries = query_result.to_dataframe()

In [19]:
df_countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 16 columns):
 #   Column                  Dtype
---  ------                  -----
 0   location_key            object
 1   date                    dbdate
 2   country_name            object
 3   aggregation_level       Int64
 4   iso_3166_1_alpha_2      object
 5   iso_3166_1_alpha_3      object
 6   subregion1_code         object
 7   subregion1_name         object
 8   subregion2_code         object
 9   subregion2_name         object
 10  population              Int64
 11  gdp_usd                 Int64
 12  nurses_per_1000         float64
 13  physicians_per_1000     float64
 14  hospital_beds_per_1000  float64
 15  health_expenditure_usd  float64
dtypes: Int64(3), dbdate(1), float64(4), object(8)
memory usage: 2.8+ GB

In [20]:
df_countries.head()

,location_key,date,country_name,aggregation_level,iso_3166_1_alpha_2,iso_3166_1_alpha_3,subregion1_code,subregion1_name,subregion2_code,subregion2_name,population,gdp_usd,nurses_per_1000,physicians_per_1000,hospital_beds_per_1000,health_expenditure_usd
0,TH_65,2021-05-30,Thailand,1,TH,THA,65,Phitsanulok,None,None,858988,<NA>,NaN,NaN,NaN,NaN
1,CZ_41_411,2021-04-19,Czech Republic,2,CZ,CZE,41,Karlovy Vary Region,411,Cheb District,87958,<NA>,NaN,NaN,NaN,NaN
2,FR_NOR_27,2022-01-04,France,2,FR,FRA,NOR,Normandy,27,Eure,601388,<NA>,NaN,NaN,NaN,NaN
3,FR_NOR_50,2022-01-20,France,2,FR,FRA,NOR,Normandy,50,Manche,492733,<NA>,NaN,NaN,NaN,NaN
4,TH_19,2021-07-09,Thailand,1,TH,THA,19,Saraburi,None,None,633460,<NA>,NaN,NaN,NaN,NaN

In [21]:
df_countries.isna().sum()

location_key                     0
date                             0
country_name                     0
aggregation_level                0
iso_3166_1_alpha_2             991
iso_3166_1_alpha_3             991
subregion1_code             244777
subregion1_name             244777
subregion2_code            1694610
subregion2_name            1694610
population                 1292264
gdp_usd                   22386690
nurses_per_1000           22577953
physicians_per_1000       22593809
hospital_beds_per_1000    22731558
health_expenditure_usd    22572007
dtype: int64

In [22]:
df_countries.describe()

,aggregation_level,population,gdp_usd,nurses_per_1000,physicians_per_1000,hospital_beds_per_1000,health_expenditure_usd
count,22756333.0,21464069.0,369643.0,178380.000000,162524.000000,24775.000000,184326.000000
mean,1.917607,746475.564754,515768862060.959473,4.393377,1.918615,3.028000,1081.069390
std,0.315939,14827961.020483,1774232681211.015625,4.116643,1.647538,2.514254,1776.806261
min,0.0,0.0,31580.0,0.073700,0.014000,0.300000,19.431646
25%,2.0,4754.0,13672802157.0,1.305425,0.414075,1.200000,82.075867
50%,2.0,17173.0,52076250947.0,3.067050,1.576550,2.300000,335.949448
75%,2.0,79690.0,217962048000.0,6.319825,2.985425,4.400000,1112.303223
max,3.0,1439323774.0,21374418877706.0,19.461400,8.421800,11.500000,10246.138672

In [23]:
import os

os.makedirs('output', exist_ok=True)

In [24]:
df_countries.to_csv('output/countries.csv')

#### **4.2.** Chcemy wygenerować statystyki dotyczące zachorowań na COVID-19 na całym świecie.

In [25]:
query = """
    SELECT location_key, date,
        new_confirmed, cumulative_confirmed,
        new_confirmed_male, new_confirmed_female,
        cumulative_confirmed_male, cumulative_confirmed_female
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

df_cases = query_result.to_dataframe()

In [26]:
df_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 8 columns):
 #   Column                       Dtype
---  ------                       -----
 0   location_key                 object
 1   date                         dbdate
 2   new_confirmed                Int64
 3   cumulative_confirmed         Int64
 4   new_confirmed_male           Int64
 5   new_confirmed_female         Int64
 6   cumulative_confirmed_male    Int64
 7   cumulative_confirmed_female  Int64
dtypes: Int64(6), dbdate(1), object(1)
memory usage: 1.5+ GB

In [27]:
df_cases.head()

,location_key,date,new_confirmed,cumulative_confirmed,new_confirmed_male,new_confirmed_female,cumulative_confirmed_male,cumulative_confirmed_female
0,BR_MS_500490,2020-01-06,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,BR_PA_150280,2021-12-31,0,573,<NA>,<NA>,<NA>,<NA>
2,BR_PA_150309,2022-02-18,23,2740,<NA>,<NA>,<NA>,<NA>
3,BR_PA_150549,2021-09-04,0,746,<NA>,<NA>,<NA>,<NA>
4,BR_PB_250260,2022-08-12,1,479,<NA>,<NA>,<NA>,<NA>

In [28]:
df_cases.isna().sum()

location_key                          0
date                                  0
new_confirmed                  10280989
cumulative_confirmed           10429736
new_confirmed_male             19346104
new_confirmed_female           19352592
cumulative_confirmed_male      19097245
cumulative_confirmed_female    19097932
dtype: int64

In [29]:
df_cases.describe()

,new_confirmed,cumulative_confirmed,new_confirmed_male,new_confirmed_female,cumulative_confirmed_male,cumulative_confirmed_female
count,12475344.0,12326597.0,3410229.0,3403741.0,3659088.0,3658401.0
mean,111.212188,35383.553739,44.010911,46.689347,10809.536452,11278.559864
std,11659.244534,613449.698206,1345.94701,1529.400253,297408.87628,333825.189107
min,-5045418.0,0.0,-2080.0,-2078.0,0.0,0.0
25%,0.0,201.0,0.0,0.0,63.0,63.0
50%,1.0,1033.0,1.0,2.0,273.0,289.0
75%,11.0,5001.0,6.0,6.0,1328.0,1405.0
max,5047094.0,92440495.0,868015.0,971715.0,35432377.0,41162212.0

Kolumny zawierające informacje dotyczące nowych przypadków zawierają wartości ujemne, co prawdopodobnie jest błędem zapisu.

In [30]:
df_cases.to_csv('output/cases.csv')

#### **4.3.** Chcemy poznać efekty COVID-19 poprzez uwypuklenie problemu śmiertelności ludzi spowodowanej wirusem.

In [31]:
query = """
    SELECT location_key, date,
        new_deceased, cumulative_deceased,
        new_deceased_male, new_deceased_female,
        cumulative_deceased_male, cumulative_deceased_female
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""

query_job = client.query(query)
query_result = query_job.result()

df_deceased = query_result.to_dataframe()

In [32]:
df_deceased.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 8 columns):
 #   Column                      Dtype
---  ------                      -----
 0   location_key                object
 1   date                        dbdate
 2   new_deceased                Int64
 3   cumulative_deceased         Int64
 4   new_deceased_male           Int64
 5   new_deceased_female         Int64
 6   cumulative_deceased_male    Int64
 7   cumulative_deceased_female  Int64
dtypes: Int64(6), dbdate(1), object(1)
memory usage: 1.5+ GB

In [33]:
df_deceased.head()

,location_key,date,new_deceased,cumulative_deceased,new_deceased_male,new_deceased_female,cumulative_deceased_male,cumulative_deceased_female
0,BR_SP_352850,2021-08-29,0,227,1,0,88,38
1,BR_SP_353205,2021-10-02,0,9,<NA>,<NA>,<NA>,<NA>
2,BR_TO_170825,2022-06-21,0,10,<NA>,<NA>,<NA>,<NA>
3,BR_TO_172100,2022-07-30,0,733,<NA>,<NA>,<NA>,<NA>
4,MX_CHP_07089,2021-05-12,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [34]:
df_deceased.isna().sum()

location_key                         0
date                                 0
new_deceased                  11089473
cumulative_deceased           11281785
new_deceased_male             20691174
new_deceased_female           20709103
cumulative_deceased_male      20512263
cumulative_deceased_female    20512950
dtype: int64

In [35]:
df_deceased.describe()

,new_deceased,cumulative_deceased,new_deceased_male,new_deceased_female,cumulative_deceased_male,cumulative_deceased_female
count,11666860.0,11474548.0,2065159.0,2047230.0,2244070.0,2243383.0
mean,1.274725,587.328897,1.20641,0.9101,355.372324,260.36508
std,88.082247,9228.731201,14.450997,11.195608,4020.342003,3015.478805
min,-63811.0,0.0,-162.0,-176.0,0.0,0.0
25%,0.0,3.0,0.0,0.0,3.0,2.0
50%,0.0,18.0,0.0,0.0,15.0,11.0
75%,0.0,80.0,0.0,0.0,75.0,57.0
max,63830.0,1005195.0,1860.0,1589.0,208279.0,167525.0

Kolumny zawierające informacje dotyczące nowych zgonów zawierają wartości ujemne, co prawdopodobnie jest błędem zapisu.

In [36]:
df_deceased.to_csv('output/deceased.csv')

#### **4.4.** Chcemy zaobserwować trendy i zależności dotyczące szczepień na COVID-19.

In [37]:
query = """
    SELECT location_key, date,
        new_persons_vaccinated, cumulative_persons_vaccinated,
        new_persons_fully_vaccinated, cumulative_persons_fully_vaccinated,
        new_vaccine_doses_administered, cumulative_vaccine_doses_administered
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""

query_job = client.query(query)
query_result = query_job.result()

df_vaccinations = query_result.to_dataframe()

In [38]:
df_vaccinations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 8 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   location_key                           object
 1   date                                   dbdate
 2   new_persons_vaccinated                 Int64
 3   cumulative_persons_vaccinated          Int64
 4   new_persons_fully_vaccinated           Int64
 5   cumulative_persons_fully_vaccinated    Int64
 6   new_vaccine_doses_administered         Int64
 7   cumulative_vaccine_doses_administered  Int64
dtypes: Int64(6), dbdate(1), object(1)
memory usage: 1.5+ GB

In [39]:
df_vaccinations.head()

,location_key,date,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered
0,US_MN_27103,2020-05-24,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,US_NC_37103,2021-09-03,<NA>,<NA>,33,3780,<NA>,<NA>
2,US_ND_38053,2021-09-03,<NA>,<NA>,8,2426,<NA>,<NA>
3,US_ND_38067,2021-06-27,<NA>,<NA>,4,2810,<NA>,<NA>
4,US_NE_31023,2021-11-22,<NA>,<NA>,7,3750,<NA>,<NA>

In [40]:
df_vaccinations.isna().sum()

location_key                                    0
date                                            0
new_persons_vaccinated                   21823540
cumulative_persons_vaccinated            21869519
new_persons_fully_vaccinated             20234181
cumulative_persons_fully_vaccinated      20233184
new_vaccine_doses_administered           21815699
cumulative_vaccine_doses_administered    21859263
dtype: int64

In [41]:
df_vaccinations.describe()

,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered
count,932793.0,886814.0,2522152.0,2523149.0,940634.0,897070.0
mean,8056.294613,1864280.623487,2481.920983,553302.972863,18887.862376,4869510.054678
std,512668.722569,22579824.378553,130763.882607,11313418.951898,364237.595311,74709178.471204
min,-9410506.0,0.0,-6867191.0,0.0,-23300109.0,0.0
25%,0.0,3702.0,0.0,3205.0,1.0,6208.25
50%,14.0,22527.0,3.0,11229.0,45.0,41738.0
75%,190.0,166171.0,36.0,40687.0,508.0,315623.25
max,450500000.0,1302773000.0,112393000.0,1270656000.0,48622062.0,3434774000.0

Kolumny zawierające informacje dotyczące nowych zaszczepień zawierają wartości ujemne, co prawdopodobnie jest błędem zapisu.

In [42]:
df_vaccinations.to_csv('output/vaccinations.csv')

#### **4.5.** Zdefiniuj własny dodatkowy przypadek.

Chcemy zbadać trendy w wyszukiwaniach fraz dotyczących wybranych zaburzeń podczas pandemii COVID-19. Rozpatrywane będą następujące wyszukiwania w Google:
- alkoholizm,
- zaburzenia lękowe,
- depresja,
- bezsenność.

In [43]:
query = """
    SELECT location_key, date,
        search_trends_alcoholism, search_trends_anxiety,
        search_trends_depression, search_trends_insomnia
    FROM bigquery-public-data.covid19_open_data.covid19_open_data
"""
query_job = client.query(query)
query_result = query_job.result()

df_searches = query_result.to_dataframe()

In [44]:
df_searches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 6 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location_key              object
 1   date                      dbdate
 2   search_trends_alcoholism  float64
 3   search_trends_anxiety     float64
 4   search_trends_depression  float64
 5   search_trends_insomnia    float64
dtypes: dbdate(1), float64(4), object(1)
memory usage: 1.0+ GB

In [45]:
df_searches.head()

,location_key,date,search_trends_alcoholism,search_trends_anxiety,search_trends_depression,search_trends_insomnia
0,BR_MT_510480,2022-07-23,NaN,NaN,NaN,NaN
1,BR_PA_150610,2022-02-26,NaN,NaN,NaN,NaN
2,BR_PB_250130,2021-04-04,NaN,NaN,NaN,NaN
3,BR_PB_250630,2022-05-23,NaN,NaN,NaN,NaN
4,BR_PE_260660,2020-08-01,NaN,NaN,NaN,NaN

In [46]:
df_searches.isna().sum()

location_key                       0
date                               0
search_trends_alcoholism    21446896
search_trends_anxiety       21009933
search_trends_depression    21338346
search_trends_insomnia      21619748
dtype: int64

In [47]:
df_searches.describe()

,search_trends_alcoholism,search_trends_anxiety,search_trends_depression,search_trends_insomnia
count,1.309437e+06,1.746400e+06,1.417987e+06,1.136585e+06
mean,4.004108e+00,7.504335e+00,4.467266e+00,2.987337e+00
std,1.081740e+00,1.740011e+00,1.137928e+00,7.299195e-01
min,8.000000e-01,1.190000e+00,7.600000e-01,4.500000e-01
25%,3.310000e+00,6.400000e+00,3.750000e+00,2.510000e+00
50%,3.870000e+00,7.390000e+00,4.350000e+00,2.920000e+00
75%,4.540000e+00,8.450000e+00,5.040000e+00,3.390000e+00
max,2.879000e+01,4.125000e+01,4.314000e+01,1.648000e+01

In [48]:
df_searches.to_csv('output/disorders.csv')

## Część 5

Połącz ze sobą wszystkie dane otrzymane w części 4. Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Pamiętaj o ciągłej konieczności zachowania czystości danych. Wynik tego zadania zapisz w pliku / plikach CSV.

In [49]:
import functools

dfs_to_combine = [df_countries, df_cases, df_deceased, df_vaccinations, df_searches]

df_combined = functools.reduce(
    lambda left, right: pd.merge(left, right, on=['location_key', 'date'], how='outer'),
    dfs_to_combine
)

In [50]:
df_combined['date'] = pd.to_datetime(df_combined['date'])

In [51]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 38 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   location_key                           object
 1   date                                   datetime64[ns]
 2   country_name                           object
 3   aggregation_level                      Int64
 4   iso_3166_1_alpha_2                     object
 5   iso_3166_1_alpha_3                     object
 6   subregion1_code                        object
 7   subregion1_name                        object
 8   subregion2_code                        object
 9   subregion2_name                        object
 10  population                             Int64
 11  gdp_usd                                Int64
 12  nurses_per_1000                        float64
 13  physicians_per_1000                    float64
 14  hospital_beds_per_1000                 float64
 15  health_expenditure_usd                 float64
 16  new_confirmed                          Int64
 17  cumulative_confirmed                   Int64
 18  new_confirmed_male                     Int64
 19  new_confirmed_female                   Int64
 20  cumulative_confirmed_male              Int64
 21  cumulative_confirmed_female            Int64
 22  new_deceased                           Int64
 23  cumulative_deceased                    Int64
 24  new_deceased_male                      Int64
 25  new_deceased_female                    Int64
 26  cumulative_deceased_male               Int64
 27  cumulative_deceased_female             Int64
 28  new_persons_vaccinated                 Int64
 29  cumulative_persons_vaccinated          Int64
 30  new_persons_fully_vaccinated           Int64
 31  cumulative_persons_fully_vaccinated    Int64
 32  new_vaccine_doses_administered         Int64
 33  cumulative_vaccine_doses_administered  Int64
 34  search_trends_alcoholism               float64
 35  search_trends_anxiety                  float64
 36  search_trends_depression               float64
 37  search_trends_insomnia                 float64
dtypes: Int64(21), datetime64[ns](1), float64(8), object(8)
memory usage: 6.9+ GB

In [52]:
df_combined.to_csv('output/combined_part_5.csv')

## Część 6

Połącz ze sobą dane otrzymane w części 5 oraz dane znajdujące się w plikach:

#### **6.1.** world_countries.csv

Podstawowe dane dotyczące krajów na całym świecie razem z historycznymi danymi na temat ich populacji. Kolejno zawarto:
- Rank – miejsce w rankingu wyznaczone na podstawie populacji.
- CCA3 – 3-literowy kod kraju lub terytorium zapisany w standardzie ISO 3166-1 alpha-3.
- Country/Territories – nazwa kraju lub terytorium.
- Capital – nazwa stolicy.
- Continent – nazwa kontynentu.
- 2022 Population – populacja kraju lub terytorium w 2022 roku.
- 2020 Population – populacja kraju lub terytorium w 2020 roku.
- 2015 Population – populacja kraju lub terytorium w 2015 roku.
- 2010 Population – populacja kraju lub terytorium w 2010 roku.
- 2000 Population – populacja kraju lub terytorium w 2000 roku.
- 1990 Population – populacja kraju lub terytorium w 1990 roku.
- 1980 Population – populacja kraju lub terytorium w 1980 roku.
- 1970 Population – populacja kraju lub terytorium w 1970 roku.
- Area (km²) – powierzchnia kraju lub terytorium podana w km².
- Density (per km²) – gęstość zaludnienia kraju lub terytorium na 1 km².
- Growth Rate – stosunek wyrażający stan populacji kraju lub terytorium w 2022 i 2021 roku, wartość zaokrąglona do 4 miejsc po przecinku.
- World Population Percentage – udział procentowy populacji kraju lub terytorium w populacji całego świata, wartość zaokrąglona do 2 miejsc po przecinku.

In [53]:
df_world_countries = pd.read_csv('data/world_countries.csv')

In [54]:
df_world_countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

In [55]:
df_world_countries.head()

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

In [56]:
df_world_countries.isna().sum()

Rank                           0
CCA3                           0
Country/Territory              0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (km²)                     0
Density (per km²)              0
Growth Rate                    0
World Population Percentage    0
dtype: int64

In [57]:
df_world_countries.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,234.000000,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,234.000000,234.000000,234.000000
mean,117.500000,3.407441e+07,3.350107e+07,3.172996e+07,2.984524e+07,2.626947e+07,2.271022e+07,1.898462e+07,1.578691e+07,5.814494e+05,452.127044,1.009577,0.427051
std,67.694165,1.367664e+08,1.355899e+08,1.304050e+08,1.242185e+08,1.116982e+08,9.783217e+07,8.178519e+07,6.779509e+07,1.761841e+06,2066.121904,0.013385,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.152845e+05,4.046760e+05,3.931490e+05,3.272420e+05,2.641158e+05,2.296142e+05,1.559970e+05,2.650000e+03,38.417875,1.001775,0.010000
50%,117.500000,5.559944e+06,5.493074e+06,5.307400e+06,4.942770e+06,4.292907e+06,3.825410e+06,3.141146e+06,2.604830e+06,8.119950e+04,95.346750,1.007900,0.070000
75%,175.750000,2.247650e+07,2.144798e+07,1.973085e+07,1.915957e+07,1.576230e+07,1.186923e+07,9.826054e+06,8.817329e+06,4.304258e+05,238.933250,1.016950,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

Dane o populacji spoza zakresu zarejestrowanych danych o COVID-19 (2020-2022) oraz lat 2015 i 2010 zostaną wyfiltrowane. Zostaną również usunięte dane o pełnych nazwach krajów, które są już zawarte w danych o COVID-19.

In [58]:
df_world_countries_filtered = df_world_countries.copy()

In [59]:
df_world_countries_filtered.drop(
    columns=[
        'Country/Territory', '1970 Population',
        '1980 Population', '1990 Population',
        '2000 Population'
    ],
    inplace=True
)

df_world_countries_filtered.rename(
    columns={
        'Rank': 'country_population_rank',
        'CCA3': 'iso_3166_1_alpha_3',
        'Continent': 'continent',
        'Capital': 'capital',
        '2022 Population': 'country_population_2022',
        '2020 Population': 'country_population_2020',
        '2015 Population': 'country_population_2015',
        '2010 Population': 'country_population_2010',
        'Area (km²)': 'country_area_sq_km',
        'Density (per km²)': 'country_population_density_per_sq_km',
        'Growth Rate': 'country_population_growth_rate',
        'World Population Percentage': 'country_world_population_percentage'
    },
    inplace=True
)

Złączenie danych o krajach z danymi z poprzednich części na podstawie 3-literowego kodu kraju.

In [60]:
df_combined = df_combined.merge(
    df_world_countries_filtered, how='left', on='iso_3166_1_alpha_3'
)

In [61]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 49 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   location_key                           object
 1   date                                   datetime64[ns]
 2   country_name                           object
 3   aggregation_level                      Int64
 4   iso_3166_1_alpha_2                     object
 5   iso_3166_1_alpha_3                     object
 6   subregion1_code                        object
 7   subregion1_name                        object
 8   subregion2_code                        object
 9   subregion2_name                        object
 10  population                             Int64
 11  gdp_usd                                Int64
 12  nurses_per_1000                        float64
 13  physicians_per_1000                    float64
 14  hospital_beds_per_1000                 float64
 15  health_expenditure_usd                 float64
 16  new_confirmed                          Int64
 17  cumulative_confirmed                   Int64
 18  new_confirmed_male                     Int64
 19  new_confirmed_female                   Int64
 20  cumulative_confirmed_male              Int64
 21  cumulative_confirmed_female            Int64
 22  new_deceased                           Int64
 23  cumulative_deceased                    Int64
 24  new_deceased_male                      Int64
 25  new_deceased_female                    Int64
 26  cumulative_deceased_male               Int64
 27  cumulative_deceased_female             Int64
 28  new_persons_vaccinated                 Int64
 29  cumulative_persons_vaccinated          Int64
 30  new_persons_fully_vaccinated           Int64
 31  cumulative_persons_fully_vaccinated    Int64
 32  new_vaccine_doses_administered         Int64
 33  cumulative_vaccine_doses_administered  Int64
 34  search_trends_alcoholism               float64
 35  search_trends_anxiety                  float64
 36  search_trends_depression               float64
 37  search_trends_insomnia                 float64
 38  country_population_rank                float64
 39  capital                                object
 40  continent                              object
 41  country_population_2022                float64
 42  country_population_2020                float64
 43  country_population_2015                float64
 44  country_population_2010                float64
 45  country_area_sq_km                     float64
 46  country_population_density_per_sq_km   float64
 47  country_population_growth_rate         float64
 48  country_world_population_percentage    float64
dtypes: Int64(21), datetime64[ns](1), float64(17), object(10)
memory usage: 8.8+ GB

#### **6.2.** GDP.csv

Wartości produktu krajowego brutto (w skrócie PKB, ang. GDP – gross domestic product) w krajach i regionach świata. Kolejno zawarto:
- Country Name – nazwa kraju lub regionu.
- Country Code – 3-literowy kod kraju lub regionu.
- Year – rok, dla którego zapisano wartość PKB.
- Value – wartość PKB podana w USD.

In [62]:
df_gdp = pd.read_csv('data/gdp.csv')

In [63]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11507 entries, 0 to 11506
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  11507 non-null  object
 1   Country Code  11507 non-null  object
 2   Year          11507 non-null  int64
 3   Value         11507 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 359.7+ KB

In [64]:
df_gdp.head()

  Country Name Country Code  Year         Value
0   Arab World          ARB  1968  2.576068e+10
1   Arab World          ARB  1969  2.843420e+10
2   Arab World          ARB  1970  3.138550e+10
3   Arab World          ARB  1971  3.642691e+10
4   Arab World          ARB  1972  4.331606e+10

In [65]:
df_gdp.isna().sum()

Country Name    0
Country Code    0
Year            0
Value           0
dtype: int64

In [66]:
df_gdp.describe()

               Year         Value
count  11507.000000  1.150700e+04
mean    1991.265230  1.005972e+12
std       15.886648  4.533056e+12
min     1960.000000  8.824448e+06
25%     1978.000000  2.056874e+09
50%     1993.000000  1.436880e+10
75%     2005.000000  1.796394e+11
max     2016.000000  7.904923e+13

In [67]:
df_gdp_filtered = df_gdp.copy()

In [68]:
df_gdp_filtered.drop(columns='Country Name', inplace=True)

df_gdp_filtered.rename(
    columns={
        'Country Code': 'iso_3166_1_alpha_3',
        'Year': 'year',
        'Value': 'country_gdp_usd_yearly'
    },
    inplace=True
)

In [69]:
df_gdp_filtered['year'].min(), df_gdp_filtered['year'].max()

(np.int64(1960), np.int64(2016))

Zbiór danych zawiera wartości PKB dla lat 1960-2016. W dalszych analizach zostaną uwzględnione dane z lat 2012-2016.

In [70]:
df_gdp_filtered = df_gdp_filtered.query('year >= 2010')

In [71]:
df_gdp_filtered_pivot = df_gdp_filtered.pivot_table(
    index='iso_3166_1_alpha_3',
    columns='year',
    values='country_gdp_usd_yearly'
).reset_index()

df_gdp_filtered_pivot.columns.name = None

df_gdp_filtered_pivot.rename(
    columns=lambda col: f"country_gdp_usd_{col}" if isinstance(col, int) else col,
    inplace=True
)

In [72]:
df_gdp_filtered_pivot.head()

,iso_3166_1_alpha_3,country_gdp_usd_2010,country_gdp_usd_2011,country_gdp_usd_2012,country_gdp_usd_2013,country_gdp_usd_2014,country_gdp_usd_2015,country_gdp_usd_2016
0,ABW,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN
1,AFG,1.593680e+10,1.793024e+10,2.053654e+10,2.004633e+10,2.005019e+10,1.921556e+10,1.946902e+10
2,AGO,8.247091e+10,1.041159e+11,1.153984e+11,1.249121e+11,1.267769e+11,1.029622e+11,9.533511e+10
3,ALB,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.133526e+10,1.186387e+10
4,AND,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.858518e+09

Złączenie danych o PKB z danymi z poprzednich części na podstawie 3-literowego kodu kraju.

In [73]:
df_combined = df_combined.merge(
    df_gdp_filtered_pivot, how='left', on='iso_3166_1_alpha_3'
)

In [74]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22756333 entries, 0 to 22756332
Data columns (total 56 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   location_key                           object
 1   date                                   datetime64[ns]
 2   country_name                           object
 3   aggregation_level                      Int64
 4   iso_3166_1_alpha_2                     object
 5   iso_3166_1_alpha_3                     object
 6   subregion1_code                        object
 7   subregion1_name                        object
 8   subregion2_code                        object
 9   subregion2_name                        object
 10  population                             Int64
 11  gdp_usd                                Int64
 12  nurses_per_1000                        float64
 13  physicians_per_1000                    float64
 14  hospital_beds_per_1000                 float64
 15  health_expenditure_usd                 float64
 16  new_confirmed                          Int64
 17  cumulative_confirmed                   Int64
 18  new_confirmed_male                     Int64
 19  new_confirmed_female                   Int64
 20  cumulative_confirmed_male              Int64
 21  cumulative_confirmed_female            Int64
 22  new_deceased                           Int64
 23  cumulative_deceased                    Int64
 24  new_deceased_male                      Int64
 25  new_deceased_female                    Int64
 26  cumulative_deceased_male               Int64
 27  cumulative_deceased_female             Int64
 28  new_persons_vaccinated                 Int64
 29  cumulative_persons_vaccinated          Int64
 30  new_persons_fully_vaccinated           Int64
 31  cumulative_persons_fully_vaccinated    Int64
 32  new_vaccine_doses_administered         Int64
 33  cumulative_vaccine_doses_administered  Int64
 34  search_trends_alcoholism               float64
 35  search_trends_anxiety                  float64
 36  search_trends_depression               float64
 37  search_trends_insomnia                 float64
 38  country_population_rank                float64
 39  capital                                object
 40  continent                              object
 41  country_population_2022                float64
 42  country_population_2020                float64
 43  country_population_2015                float64
 44  country_population_2010                float64
 45  country_area_sq_km                     float64
 46  country_population_density_per_sq_km   float64
 47  country_population_growth_rate         float64
 48  country_world_population_percentage    float64
 49  country_gdp_usd_2010                   float64
 50  country_gdp_usd_2011                   float64
 51  country_gdp_usd_2012                   float64
 52  country_gdp_usd_2013                   float64
 53  country_gdp_usd_2014                   float64
 54  country_gdp_usd_2015                   float64
 55  country_gdp_usd_2016                   float64
dtypes: Int64(21), datetime64[ns](1), float64(24), object(10)
memory usage: 9.9+ GB

Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Pamiętaj o ciągłej konieczności zachowania czystości danych. Wynik tego zadania zapisz w pliku / plikach CSV.

In [75]:
df_combined.to_csv('output/combined_part_6.csv')

## Część 7
**Misja dodatkowa – Więcej danych**

Znajdź 3 dodatkowe zbiory danych, które uważasz, że rozwijają w ciekawy sposób temat ostatniej pandemii. Powtórz dla nich analogiczne czynności z części 4, a następnie połącz je z danymi z części 6. Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Pamiętaj o ciągłej konieczności zachowania czystości danych. Wynik tego zadania zapisz w pliku / plikach CSV.

#### **Zbiór 1.** Dane dotyczące wartości produktu krajowego brutto w krajach i regionach świata, rozszerzające dane z części 6.2.
https://data.worldbank.org/indicator/NY.GDP.MKTP.CD

In [76]:
df_gdp_augmented = pd.read_csv('data/gdp_extended.csv', delimiter=',', skiprows=4)

In [77]:
df_gdp_augmented.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            157 non-null    float64
 7   1963            157 non-null    float64
 8   1964            157 non-null    float64
 9   1965            163 non-null    float64
 10  1966            164 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            259 non-null    float64
 60  2016            258 non-null    float64
 61  2017            258 non-null    float64
 62  2018            258 non-null    float64
 63  2019            258 non-null    float64
 64  2020            257 non-null    float64
 65  2021            257 non-null    float64
 66  2022            254 non-null    float64
 67  2023            242 non-null    float64
 68  Unnamed: 68     0 non-null      float64
dtypes: float64(65), object(4)
memory usage: 143.5+ KB

In [78]:
df_gdp_augmented.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.962907e+09,2.983635e+09,3.092429e+09,3.276184e+09,3.395799e+09,2.481857e+09,2.929447e+09,3.279344e+09,3.648573e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.421063e+10,2.496398e+10,2.707880e+10,3.177575e+10,3.028579e+10,3.381317e+10,...,8.982778e+11,8.289428e+11,9.729989e+11,1.012306e+12,1.009721e+12,9.333918e+11,1.085745e+12,1.191423e+12,1.245472e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.723305e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190495e+10,1.270788e+10,1.363076e+10,1.446909e+10,1.580376e+10,1.692109e+10,...,7.717669e+11,6.943610e+11,6.878492e+11,7.704950e+11,8.264838e+11,7.898017e+11,8.493124e+11,8.839739e+11,7.991060e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.049642e+10,5.276162e+10,7.369015e+10,7.945069e+10,7.089796e+10,4.850156e+10,6.650513e+10,1.043997e+11,8.482465e+10,NaN

In [79]:
df_gdp_augmented.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              115
                 ...
2020                9
2021                9
2022               12
2023               24
Unnamed: 68       266
Length: 69, dtype: int64

In [80]:
df_gdp_augmented.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
count,1.510000e+02,1.540000e+02,1.570000e+02,1.570000e+02,1.570000e+02,1.630000e+02,1.640000e+02,1.670000e+02,1.680000e+02,1.680000e+02,...,2.590000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.570000e+02,2.570000e+02,2.540000e+02,2.420000e+02,0.0
mean,6.786171e+10,6.982251e+10,7.327492e+10,7.908218e+10,8.680328e+10,9.133482e+10,9.793328e+10,1.014971e+11,1.086794e+11,1.203480e+11,...,2.382043e+12,2.424134e+12,2.597268e+12,2.765285e+12,2.807353e+12,2.736278e+12,3.141029e+12,3.307885e+12,3.618640e+12,NaN
std,2.019254e+11,2.116016e+11,2.257269e+11,2.427310e+11,2.657976e+11,2.844773e+11,3.088386e+11,3.257876e+11,3.515860e+11,3.876032e+11,...,8.174322e+12,8.328694e+12,8.865044e+12,9.440413e+12,9.580867e+12,9.368340e+12,1.069643e+13,1.114471e+13,1.190401e+13,NaN
min,1.201202e+07,1.159202e+07,1.254164e+07,1.283330e+07,1.341663e+07,1.359393e+07,1.446908e+07,1.583511e+07,1.460000e+07,1.585000e+07,...,3.681194e+07,4.162906e+07,4.527660e+07,4.801526e+07,5.412320e+07,5.174659e+07,6.019641e+07,5.906598e+07,6.228031e+07,NaN
25%,5.079241e+08,5.007338e+08,5.740911e+08,5.862949e+08,5.828164e+08,5.956572e+08,6.450667e+08,6.311234e+08,6.211906e+08,6.574670e+08,...,8.766202e+09,8.620784e+09,9.193745e+09,9.928840e+09,1.011166e+10,9.516738e+09,1.007135e+10,1.246361e+10,1.543170e+10,NaN
50%,3.359404e+09,3.330233e+09,3.308913e+09,3.988462e+09,4.016794e+09,3.817227e+09,4.153527e+09,3.532700e+09,4.529031e+09,5.087251e+09,...,4.871750e+10,4.806565e+10,5.277001e+10,5.609719e+10,5.775248e+10,5.366864e+10,6.152928e+10,6.970415e+10,8.383752e+10,NaN
75%,3.325071e+10,3.282977e+10,3.184162e+10,3.657288e+10,3.319881e+10,3.464910e+10,3.720117e+10,3.658090e+10,3.851340e+10,4.334334e+10,...,4.973625e+11,5.042315e+11,5.341521e+11,5.491441e+11,5.421641e+11,5.451476e+11,6.371869e+11,6.799031e+11,1.021922e+12,NaN
max,1.371947e+12,1.445951e+12,1.550598e+12,1.669570e+12,1.830168e+12,1.994298e+12,2.161754e+12,2.293944e+12,2.478900e+12,2.738144e+12,...,7.547247e+13,7.670255e+13,8.171204e+13,8.688484e+13,8.814985e+13,8.576301e+13,9.784830e+13,1.017709e+14,1.061717e+14,NaN

In [81]:
df_gdp_augmented_filtered = df_gdp_augmented.copy()

Dane zawierają wartości PKB dla lat 1960-2023. W dalszych analizach zostaną uwzględnione dane z lat 2017-2023, wzbogacające dane z części 6.2. z lat 2010-2016.

In [82]:
df_gdp_augmented_filtered = df_gdp_augmented_filtered[[
    'Country Code', '2017', '2018', '2019',
    '2020', '2021', '2022', '2023'
]]

df_gdp_augmented_filtered.rename(
    columns={
        'Country Code': 'iso_3166_1_alpha_3',
        '2017': 'country_gdp_usd_2017',
        '2018': 'country_gdp_usd_2018',
        '2019': 'country_gdp_usd_2019',
        '2020': 'country_gdp_usd_2020',
        '2021': 'country_gdp_usd_2021',
        '2022': 'country_gdp_usd_2022',
        '2023': 'country_gdp_usd_2023'
    },
    inplace=True
)

#### **Zbiór 2.** Dane dotyczące jakości powietrza w poszczególnych stanach i hrabstwach Stanów Zjednoczonych w latach 2020-2022.
https://aqs.epa.gov/aqsweb/airdata/download_files.html

In [83]:
df_aqi_2020 = pd.read_csv('data/daily_aqi_by_county_2020.csv')
df_aqi_2021 = pd.read_csv('data/daily_aqi_by_county_2021.csv')
df_aqi_2022 = pd.read_csv('data/daily_aqi_by_county_2022.csv')

df_air_quality = pd.concat([df_aqi_2020, df_aqi_2021, df_aqi_2022])

In [84]:
df_air_quality.info()

<class 'pandas.core.frame.DataFrame'>
Index: 976100 entries, 0 to 324421
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State Name                 976100 non-null  object
 1   county Name                976100 non-null  object
 2   State Code                 976100 non-null  int64
 3   County Code                976100 non-null  int64
 4   Date                       976100 non-null  object
 5   AQI                        976100 non-null  int64
 6   Category                   976100 non-null  object
 7   Defining Parameter         976100 non-null  object
 8   Defining Site              976100 non-null  object
 9   Number of Sites Reporting  976100 non-null  int64
dtypes: int64(4), object(6)
memory usage: 81.9+ MB

In [85]:
df_air_quality.head()

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2020-01-01,56,Moderate,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2020-01-04,18,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2020-01-07,18,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2020-01-10,51,Moderate,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2020-01-13,38,Good,PM2.5,01-003-0010,1

In [86]:
df_air_quality.isna().sum()

State Name                   0
county Name                  0
State Code                   0
County Code                  0
Date                         0
AQI                          0
Category                     0
Defining Parameter           0
Defining Site                0
Number of Sites Reporting    0
dtype: int64

In [87]:
df_air_quality.describe()

          State Code    County Code            AQI  Number of Sites Reporting
count  976100.000000  976100.000000  976100.000000              976100.000000
mean       30.348972      80.176012      42.253111                   1.999282
std        16.227468      89.943306      26.268488                   2.454800
min         1.000000       1.000000       0.000000                   1.000000
25%        17.000000      23.000000      31.000000                   1.000000
50%        30.000000      59.000000      40.000000                   1.000000
75%        42.000000     107.000000      51.000000                   2.000000
max        80.000000     840.000000    8368.000000                  34.000000

In [88]:
df_air_quality_filtered = df_air_quality.copy()

In [89]:
df_air_quality_filtered = df_air_quality_filtered[['State Name', 'county Name', 'Date', 'AQI', 'Defining Parameter']]

df_air_quality_filtered.rename(
    columns={
        'State Name': 'subregion1_name',
        'county Name': 'subregion2_name',
        'Date': 'date',
        'AQI': 'aqi_daily',
        'Defining Parameter': 'aqi_defining_parameter'
    },
    inplace=True
)

df_air_quality_filtered['date'] = pd.to_datetime(df_air_quality_filtered['date'])

In [90]:
df_air_quality_filtered['aqi_defining_parameter'].value_counts()

aqi_defining_parameter
Ozone    466883
PM2.5    465929
PM10      30150
NO2       11389
CO         1749
Name: count, dtype: int64

W zbiorze dot. COVID-19, nazwy hrabstw mają dopisek 'County', co zostanie zastosowane również w zbiorze dot. jakości powietrza.

In [91]:
df_air_quality_filtered['subregion2_name'] = (
    df_air_quality_filtered['subregion2_name']
    .apply(lambda x: x + ' County')
)

In [92]:
df_air_quality_filtered.head()

  subregion1_name subregion2_name       date  aqi_daily aqi_defining_parameter
0         Alabama  Baldwin County 2020-01-01         56                  PM2.5
1         Alabama  Baldwin County 2020-01-04         18                  PM2.5
2         Alabama  Baldwin County 2020-01-07         18                  PM2.5
3         Alabama  Baldwin County 2020-01-10         51                  PM2.5
4         Alabama  Baldwin County 2020-01-13         38                  PM2.5

#### **Zbiór 3.** Dane dotyczące generacji, emisji i zapotrzebowania energii elektrycznej w poszczególnych krajach świata.
https://ember-energy.org/data/monthly-electricity-data/

In [93]:
df_electricity = pd.read_csv('data/electricity.csv')

In [94]:
df_electricity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 464550 entries, 0 to 464549
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Area                 464550 non-null  object
 1   Country code         414616 non-null  object
 2   Date                 464550 non-null  object
 3   Area type            464550 non-null  object
 4   Continent            414616 non-null  object
 5   Ember region         414616 non-null  object
 6   EU                   414616 non-null  float64
 7   OECD                 414616 non-null  float64
 8   G20                  414616 non-null  float64
 9   G7                   414616 non-null  float64
 10  ASEAN                414616 non-null  float64
 11  Category             464550 non-null  object
 12  Subcategory          464550 non-null  object
 13  Variable             464550 non-null  object
 14  Unit                 464550 non-null  object
 15  Value                462381 non-null  float64
 16  YoY absolute change  289738 non-null  float64
 17  YoY % change         245539 non-null  float64
dtypes: float64(8), object(10)
memory usage: 63.8+ MB

In [95]:
df_electricity.head()

,Area,Country code,Date,Area type,Continent,Ember region,EU,OECD,G20,G7,ASEAN,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,Argentina,ARG,2018-01-01,Country,South America,Latin America and Caribbean,0.0,0.0,1.0,0.0,0.0,Electricity demand,Demand,Demand,TWh,12.77,NaN,NaN
1,Argentina,ARG,2018-01-01,Country,South America,Latin America and Caribbean,0.0,0.0,1.0,0.0,0.0,Electricity generation,Aggregate fuel,Clean,%,34.57,NaN,NaN
2,Argentina,ARG,2018-01-01,Country,South America,Latin America and Caribbean,0.0,0.0,1.0,0.0,0.0,Electricity generation,Aggregate fuel,Fossil,%,65.44,NaN,NaN
3,Argentina,ARG,2018-01-01,Country,South America,Latin America and Caribbean,0.0,0.0,1.0,0.0,0.0,Electricity generation,Aggregate fuel,Gas and Other Fossil,%,63.40,NaN,NaN
4,Argentina,ARG,2018-01-01,Country,South America,Latin America and Caribbean,0.0,0.0,1.0,0.0,0.0,Electricity generation,Aggregate fuel,"Hydro, Bioenergy and Other Renewables",%,29.08,NaN,NaN

In [96]:
df_electricity.isna().sum()

Area                        0
Country code            49934
Date                        0
Area type                   0
Continent               49934
Ember region            49934
EU                      49934
OECD                    49934
G20                     49934
G7                      49934
ASEAN                   49934
Category                    0
Subcategory                 0
Variable                    0
Unit                        0
Value                    2169
YoY absolute change    174812
YoY % change           219011
dtype: int64

In [97]:
df_electricity.describe()

,EU,OECD,G20,G7,ASEAN,Value,YoY absolute change,YoY % change
count,414616.000000,414616.000000,414616.000000,414616.000000,414616.000000,462381.000000,289738.000000,245539.000000
mean,0.352198,0.527175,0.241824,0.120979,0.068133,30.427111,0.074001,8.289965
std,0.477656,0.499262,0.428189,0.326104,0.251974,111.925657,15.283876,83.516853
min,0.000000,0.000000,0.000000,0.000000,0.000000,-9.270000,-1045.650000,-14000.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.070000,-0.030000,-6.660000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.370000,0.000000,0.000000
75%,1.000000,1.000000,0.000000,0.000000,0.000000,14.030000,0.100000,12.750000
max,1.000000,1.000000,1.000000,1.000000,1.000000,2750.970000,490.200000,8700.000000

W kolumnie 'Country code' znajdują się brakujące wartości, należy zbadać czy wiersze z brakującymi wartościami będą istotne dla analizy.

In [98]:
df_electricity.query('`Country code`.isnull()')['Area'].value_counts()

Area
North America                  9000
EU                             6100
Europe                         6100
Asia                           3650
G20                            3650
G7                             3650
Latin America and Caribbean    3650
OECD                           3650
ASEAN                          3550
World                          3550
Oceania                        3384
Name: count, dtype: int64

Brakujące wartości w kolumnie 'Country code' dotyczą obszarów, które nie są krajami, dlatego zostaną usunięte.

In [99]:
df_electricity.dropna(subset=['Country code'], inplace=True)

In [100]:
df_electricity['Category'].value_counts()

Category
Electricity generation    251460
Power sector emissions    140388
Electricity demand          9772
Electricity imports         9772
Electricity prices          3224
Name: count, dtype: int64

In [101]:
print(
    'Observations date range:',
    df_electricity['Date'].min(),
    '-',
    df_electricity['Date'].max()
)

Observations date range: 1998-12-01 - 2025-02-01

In [102]:
df_electricity_filtered = df_electricity.copy()

Do dalszej analizy zostaną wykorzystane dane dotyczące łącznej generacji energii elektrycznej oraz łącznego zapotrzebowania na energię elektryczną, pozostałe dane zostaną wyfiltrowane.

In [103]:
df_electricity_filtered = df_electricity_filtered.query(
    'Variable in ("Demand", "Total Generation")'
)

In [104]:
df_electricity_filtered.isna().sum()

Area                      0
Country code              0
Date                      0
Area type                 0
Continent                 0
Ember region              0
EU                        0
OECD                      0
G20                       0
G7                        0
ASEAN                     0
Category                  0
Subcategory               0
Variable                  0
Unit                      0
Value                     0
YoY absolute change    2112
YoY % change           2112
dtype: int64

In [105]:
df_electricity_filtered = df_electricity_filtered[
    ['Country code', 'Date', 'Variable', 'Value']
]

df_electricity_filtered.rename(
    columns={
        'Country code': 'iso_3166_1_alpha_3',
        'Date': 'date',
        'Variable': 'category',
        'Value': 'value'
    },
    inplace=True
)

In [106]:
df_electricity_filtered['date'] = pd.to_datetime(df_electricity_filtered['date'])

df_electricity_filtered = df_electricity_filtered[
    df_electricity_filtered['date'].between('2020-01-01', '2022-12-31')
]

In [107]:
df_electricity_filtered_pivot = df_electricity_filtered.pivot_table(
    index=['iso_3166_1_alpha_3', 'date'],
    columns='category',
    values='value'
).reset_index()

df_electricity_filtered_pivot.columns.name = None

df_electricity_filtered_pivot.rename(
    columns={
        'Demand': 'country_electricity_demand_twh_monthly',
        'Total Generation': 'country_electricity_generation_twh_monthly'
    },
    inplace=True
)

In [108]:
df_electricity_filtered_pivot.head()

,iso_3166_1_alpha_3,date,country_electricity_demand_twh_monthly,country_electricity_generation_twh_monthly
0,ARG,2020-01-01,12.44,12.43
1,ARG,2020-02-01,11.20,11.19
2,ARG,2020-03-01,11.55,11.70
3,ARG,2020-04-01,8.92,8.99
4,ARG,2020-05-01,10.04,10.07

#### Złączenie zbiorów danych z części 6 z dodatkowymi zbiorami danych.

In [109]:
df_combined = df_combined.merge(
    df_gdp_augmented_filtered,
    how='left',
    on='iso_3166_1_alpha_3'
)

df_combined = df_combined.merge(
    df_air_quality_filtered,
    how='left',
    on=['subregion1_name', 'subregion2_name', 'date']
)

df_combined['month'] = df_combined['date'].dt.to_period('M')
df_electricity_filtered_pivot['month'] = df_electricity_filtered['date'].dt.to_period('M')

df_combined = df_combined.merge(
    df_electricity_filtered_pivot.drop(columns='date'),
    how='left',
    on=['iso_3166_1_alpha_3', 'month']
)

df_combined.drop(columns='month', inplace=True)

In [110]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22760647 entries, 0 to 22760646
Data columns (total 67 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   location_key                                object
 1   date                                        datetime64[ns]
 2   country_name                                object
 3   aggregation_level                           Int64
 4   iso_3166_1_alpha_2                          object
 5   iso_3166_1_alpha_3                          object
 6   subregion1_code                             object
 7   subregion1_name                             object
 8   subregion2_code                             object
 9   subregion2_name                             object
 10  population                                  Int64
 11  gdp_usd                                     Int64
 12  nurses_per_1000                             float64
 13  physicians_per_1000                         float64
 14  hospital_beds_per_1000                      float64
 15  health_expenditure_usd                      float64
 16  new_confirmed                               Int64
 17  cumulative_confirmed                        Int64
 18  new_confirmed_male                          Int64
 19  new_confirmed_female                        Int64
 20  cumulative_confirmed_male                   Int64
 21  cumulative_confirmed_female                 Int64
 22  new_deceased                                Int64
 23  cumulative_deceased                         Int64
 24  new_deceased_male                           Int64
 25  new_deceased_female                         Int64
 26  cumulative_deceased_male                    Int64
 27  cumulative_deceased_female                  Int64
 28  new_persons_vaccinated                      Int64
 29  cumulative_persons_vaccinated               Int64
 30  new_persons_fully_vaccinated                Int64
 31  cumulative_persons_fully_vaccinated         Int64
 32  new_vaccine_doses_administered              Int64
 33  cumulative_vaccine_doses_administered       Int64
 34  search_trends_alcoholism                    float64
 35  search_trends_anxiety                       float64
 36  search_trends_depression                    float64
 37  search_trends_insomnia                      float64
 38  country_population_rank                     float64
 39  capital                                     object
 40  continent                                   object
 41  country_population_2022                     float64
 42  country_population_2020                     float64
 43  country_population_2015                     float64
 44  country_population_2010                     float64
 45  country_area_sq_km                          float64
 46  country_population_density_per_sq_km        float64
 47  country_population_growth_rate              float64
 48  country_world_population_percentage         float64
 49  country_gdp_usd_2010                        float64
 50  country_gdp_usd_2011                        float64
 51  country_gdp_usd_2012                        float64
 52  country_gdp_usd_2013                        float64
 53  country_gdp_usd_2014                        float64
 54  country_gdp_usd_2015                        float64
 55  country_gdp_usd_2016                        float64
 56  country_gdp_usd_2017                        float64
 57  country_gdp_usd_2018                        float64
 58  country_gdp_usd_2019                        float64
 59  country_gdp_usd_2020                        float64
 60  country_gdp_usd_2021                        float64
 61  country_gdp_usd_2022                        float64
 62  country_gdp_usd_2023                        float64
 63  aqi_daily                                   float64
 64  aqi_defining_parameter                      object
 65  country_electricity_demand_twh_monthly      float64
 66  country_electricity_generation_twh_monthly  float64
dtypes: Int64(21), datetime64[ns](1), float64(34), object(11)
memory usage: 11.8+ GB

In [111]:
df_combined.to_csv('output/combined_part_7.csv')